yarnPath: .yarn/releases/yarn-4.5.1.cjs
nodeLinker: pnp
# packageExtensions:
#     swiper@*:
#         peerDependencies:
#             react: '*'
#             react-dom: '*'
#         dependencies:
#             dom7: '*'
#             ssr-window: '*'
