name: PR Build Check

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Build
              run: yarn build

            - name: Fail on error
              run: exit 1
              if: failure()
